package vista;

import controlador.Controlador;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author Franco
 */
public class Ventana extends javax.swing.JFrame
{
    /** Creates new form Ventana */
    public Ventana()
    {
        Controlador controlador = new Controlador(this);
        initComponents();
        this.jtaErrores.setEditable(false);
        this.jtaMensajes.setEditable(false);
        this.jtfCadenaComando.setText("");
        this.setSize(500, 500);
        this.setLocationRelativeTo(null);
        this.jtfCadenaComando.addKeyListener(controlador);
        this.jbEjecutar.addActionListener(controlador);
    }

    public String getCadenaComando()
    {
        return this.jtfCadenaComando.getText();
    }
    
    public JButton getJbEjecutar()
    {
        return this.jbEjecutar;
    }
    
    public JTextField getJTextField()
    {
        return this.jtfCadenaComando;
    }
    
    public void mensajeError(int i) 
    {
        switch (i)
        {
            case (0): this.addMensajeError("Error000: Comando mal formado.\n");
            break;
            case (1): this.addMensajeError("Error001: Operacion no conocida.\n");
            break;
            case (2): this.addMensajeError("Error002: Consulta mal construida. \n");
            break;
            case (3): this.addMensajeError("Error003: Archivo inexistente.\n");
            break;  
            case (4): this.addMensajeError("Error004: Operacion no realizable.\n");
            break;
            case (5): this.addMensajeError("Error005: Dato inexistente.\n");
            break;
        }
        
    }
    
    public void addMensajeError(String mensaje)
    {
        this.jtaErrores.append(mensaje+"\n");
    }
    
    public void addMensaje(String mensaje)
    {
        this.jtaMensajes.append(mensaje+"\n");
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents()//GEN-BEGIN:initComponents
    {

        jpCadena_Boton = new javax.swing.JPanel();
        jpCadena = new javax.swing.JPanel();
        jtfCadenaComando = new javax.swing.JTextField();
        jpBoton = new javax.swing.JPanel();
        jbEjecutar = new javax.swing.JButton();
        jpMsjEventos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaMensajes = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaErrores = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpCadena_Boton.setLayout(new java.awt.GridLayout(1, 2));

        jpCadena.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadena de Comandos"));
        jpCadena.setLayout(new java.awt.BorderLayout());

        jtfCadenaComando.setText("jTextField1");
        jpCadena.add(jtfCadenaComando, java.awt.BorderLayout.CENTER);

        jpCadena_Boton.add(jpCadena);

        jbEjecutar.setText("Ejecutar");
        jpBoton.add(jbEjecutar);

        jpCadena_Boton.add(jpBoton);

        getContentPane().add(jpCadena_Boton, java.awt.BorderLayout.PAGE_START);

        jpMsjEventos.setLayout(new java.awt.GridLayout(1, 2));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        jtaMensajes.setColumns(20);
        jtaMensajes.setRows(5);
        jtaMensajes.setBorder(null);
        jScrollPane2.setViewportView(jtaMensajes);

        jpMsjEventos.add(jScrollPane2);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Errores"));

        jtaErrores.setColumns(20);
        jtaErrores.setRows(5);
        jtaErrores.setBorder(null);
        jScrollPane1.setViewportView(jtaErrores);

        jpMsjEventos.add(jScrollPane1);

        getContentPane().add(jpMsjEventos, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(Ventana.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(Ventana.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(Ventana.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(Ventana.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable()
            {
                public void run()
                {
                    new Ventana().setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbEjecutar;
    private javax.swing.JPanel jpBoton;
    private javax.swing.JPanel jpCadena;
    private javax.swing.JPanel jpCadena_Boton;
    private javax.swing.JPanel jpMsjEventos;
    private javax.swing.JTextArea jtaErrores;
    private javax.swing.JTextArea jtaMensajes;
    private javax.swing.JTextField jtfCadenaComando;
    // End of variables declaration//GEN-END:variables

}
